# https://docs.aws.amazon.com/ko_kr/codedeploy/latest/userguide/reference-appspec-file-structure.html#server-appspec-structure
version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/github_action
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  ApplicationStart:
    - location: deploy_scripts/gh_deploy.sh
      timeout: 60
      runas: ubuntu
    - location: deploy_scripts/switch.sh
      timeout: 60
      runas: ubuntu
