version: "3.8"
services:
  my3d-database:
    container_name: my3d-database
    build:
      dockerfile: Dockerfile
      context: ./database
    image: mariadb:10
    environment:
      - MARIADB_DATABASE=my3d
      - MARIADB_ROOT_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    volumes:
      - ./database/conf.d:/etc/mysql/conf.d
      - ./database/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "3307:3307"
