spring:
  profiles:
    active: local # default
    group:
      local:
        - common
        - security
        - mail
      prod1:
        - common
        - security
        - mail
        - prod
      prod2:
        - common
        - security
        - mail
        - prod
      test:
        - security
        - mail

---

spring:
  config.activate.on-profile: local
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  devtools.livereload:
    enabled: true
    port: 35730

---

spring:
  config.activate.on-profile: prod
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
server.tomcat.use-relative-redirects: true

---

spring:
  config.activate.on-profile: prod1
server.port: 8080

---

spring:
  config.activate.on-profile: prod2
server.port: 8081

---

spring:
  config.activate.on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true
    defer-datasource-initialization: true
    open-in-view: false
  sql.init.mode: always
nts.service-key: ${NTS_BUSINESS_KEY}
admin.email: "admin@gmail.com"
jwt:
  token:
    cookie-name: "token"
    secret-key: "aaaaagaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" # >= 256bits
    expired-time-ms: 2592000000
