spring:
  config.activate.on-profile: common
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 10
  thymeleaf3.decoupled-logic: true
aws:
  bucketName: ${S3_BUCKET_NAME}
  s3:
    url: ${S3_URL}
