spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  security.oauth2.client.registration.kakao:
    client-id: ${KAKAO_OAUTH_CLIENT_ID}
    client-secret: ${KAKAO_OAUTH_CLIENT_SECRET}
  mail:
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
jwt.token:
    cookie-name: ${JWT_COOKIE_NAME}
    secret-key: ${JWT_SECRET_KEY} # >= 256bits
aws:
  bucketName: ${S3_BUCKET_NAME}
  s3.url: ${S3_URL}
nts.service-key: ${NTS_BUSINESS_KEY}
admin.email: ${ADMIN_EMAIL}
