spring:
  config.activate.on-profile: security
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_OAUTH_CLIENT_ID}
            client-secret: ${GOOGLE_OAUTH_CLIENT_SECRET}
            scope:
              - profile
              - email
          naver:
            client-id: ${NAVER_OAUTH_CLIENT_ID}
            client-secret: ${NAVER_OAUTH_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - name
              - email
          kakao:
            # REST API 키
            client-id: ${KAKAO_OAUTH_CLIENT_ID}
            # 보안 > Client Secret 코드
            client-secret: ${KAKAO_OAUTH_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-authentication-method: POST
            scope:
              - "account_email"
              - "profile_nickname"
        provider:
          naver:
            # https://developers.naver.com/docs/login/devguide/devguide.md#3-4-2-%EB%84%A4%EC%9D%B4%EB%B2%84-%EB%A1%9C%EA%B7%B8%EC%9D%B8-%EC%97%B0%EB%8F%99-url-%EC%83%9D%EC%84%B1%ED%95%98%EA%B8%B0
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            # https://developers.naver.com/docs/login/devguide/devguide.md#3-4-4-%EC%A0%91%EA%B7%BC-%ED%86%A0%ED%81%B0-%EB%B0%9C%EA%B8%89-%EC%9A%94%EC%B2%AD
            token-uri: https://nid.naver.com/oauth2.0/token
            # https://developers.naver.com/docs/login/devguide/devguide.md#3-4-5-%EC%A0%91%EA%B7%BC-%ED%86%A0%ED%81%B0%EC%9D%84-%EC%9D%B4%EC%9A%A9%ED%95%98%EC%97%AC-%ED%94%84%EB%A1%9C%ED%95%84-api-%ED%98%B8%EC%B6%9C%ED%95%98%EA%B8%B0
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            # https://developers.kakao.com/docs/latest/ko/kakaologin/rest-api#request-code
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            # https://developers.kakao.com/docs/latest/ko/kakaologin/rest-api#request-token
            token-uri: https://kauth.kakao.com/oauth/token
            # https://developers.kakao.com/docs/latest/ko/kakaologin/rest-api#req-user-info
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
jwt:
  token:
    cookie-name: ${JWT_COOKIE_NAME}
    secret-key: ${JWT_SECRET_KEY} # >= 256bits
    access-expired-ms: 1800000 # 30 * 60000 = 30 minutes
    refresh-expired-ms: 86400000 # 24 * 3600000 = 24 hours
nts.service-key: ${NTS_BUSINESS_KEY}
