package joo.project.my3d.domain.constant;

public enum ArticleCategory {
    ANIMALS_PETS,
    ARCHITECTURE,
    ART_ABSTRACT,
    CARS_VEHICLES,
    CHARACTERS_CREATURES,
    CULTURAL_HERITAGE_HISTORY,
    ELECTRONICS_GADGETS,
    FASHION_STYLE,
    FOOD_DRINK,
    FURNITURE_HOME,
    MUSIC,
    NATURE_PLANTS,
    NEWS_POLITICS,
    PEOPLE,
    PLACES_TRAVEL,
    SCIENCE_TECHNOLOGY,
    SPORTS_FITNESS,
    WEAPONS_MILITARY
}
